# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yunxin\Desktop\invPen\sever_si.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 560)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(320, 50, 280, 186))
        self.widget.setObjectName("widget")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.rodMassEdit = QtWidgets.QLineEdit(self.widget)
        self.rodMassEdit.setObjectName("rodMassEdit")
        self.gridLayout_2.addWidget(self.rodMassEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.rodLengthEdit = QtWidgets.QLineEdit(self.widget)
        self.rodLengthEdit.setObjectName("rodLengthEdit")
        self.gridLayout_2.addWidget(self.rodLengthEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.carMassEdit = QtWidgets.QLineEdit(self.widget)
        self.carMassEdit.setObjectName("carMassEdit")
        self.gridLayout_2.addWidget(self.carMassEdit, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.modelButton = QtWidgets.QPushButton(self.widget)
        self.modelButton.setObjectName("modelButton")
        self.horizontalLayout_2.addWidget(self.modelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.vectorDisturbEdit = QtWidgets.QLineEdit(self.widget)
        self.vectorDisturbEdit.setObjectName("vectorDisturbEdit")
        self.gridLayout.addWidget(self.vectorDisturbEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.velocityDisturbEdit = QtWidgets.QLineEdit(self.widget)
        self.velocityDisturbEdit.setObjectName("velocityDisturbEdit")
        self.gridLayout.addWidget(self.velocityDisturbEdit, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.angleDisturbEdit = QtWidgets.QLineEdit(self.widget)
        self.angleDisturbEdit.setObjectName("angleDisturbEdit")
        self.gridLayout.addWidget(self.angleDisturbEdit, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.omegaDisturbEdit = QtWidgets.QLineEdit(self.widget)
        self.omegaDisturbEdit.setObjectName("omegaDisturbEdit")
        self.gridLayout.addWidget(self.omegaDisturbEdit, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.disturbButton = QtWidgets.QPushButton(self.widget)
        self.disturbButton.setObjectName("disturbButton")
        self.horizontalLayout.addWidget(self.disturbButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "杆质量"))
        self.label_2.setText(_translate("Form", "杆长度"))
        self.label_3.setText(_translate("Form", "车质量"))
        self.modelButton.setText(_translate("Form", "模型设置"))
        self.label_4.setText(_translate("Form", "位移扰动"))
        self.label_5.setText(_translate("Form", "速度扰动"))
        self.label_6.setText(_translate("Form", "角度扰动"))
        self.label_7.setText(_translate("Form", "角速度扰动"))
        self.disturbButton.setText(_translate("Form", "扰动设置"))
